### ISSUE TITLE
emmake compilation

### ISSUE THREAD

**Issue by sergiomtzlosa** [JeroenMulkers/mumax-view#2]
Hi,

Thank you for this great piece of software. I love it.

I tried to compile to code but I get the following issue:
 
`Scanning dependencies of target mumax-view
[  7%] Building CXX object CMakeFiles/mumax-view.dir/src/arrow.cpp.o
/home/sid/mumax-view/src/arrow.cpp:1:10: fatal error: 'glm/glm.hpp' file not found
#include <glm/glm.hpp>
         ^~~~~~~~~~~~~
1 error generated.
em++: error: '/home/sid/emsdk/upstream/bin/clang++ -target wasm32-unknown-emscripten -D__EMSCRIPTEN_major__=1 -D__EMSCRIPTEN_minor__=39 -D__EMSCRIPTEN_tiny__=18 -D_LIBCPP_ABI_VERSION=2 -Dunix -D__unix -D__unix__ -Werror=implicit-function-declaration -Xclang -nostdsysteminc -Xclang -isystem/home/sid/emsdk/upstream/emscripten/system/include/libcxx -Xclang -isystem/home/sid/emsdk/upstream/emscripten/system/lib/libcxxabi/include -Xclang -isystem/home/sid/emsdk/upstream/emscripten/system/lib/libunwind/include -Xclang -isystem/home/sid/emsdk/upstream/emscripten/system/include/compat -Xclang -isystem/home/sid/emsdk/upstream/emscripten/system/include -Xclang -isystem/home/sid/emsdk/upstream/emscripten/system/include/libc -Xclang -isystem/home/sid/emsdk/upstream/emscripten/system/lib/libc/musl/arch/emscripten -Xclang -isystem/home/sid/emsdk/upstream/emscripten/system/local/include -Xclang -isystem/home/sid/emsdk/upstream/emscripten/system/include/SSE -Xclang -isystem/home/sid/emsdk/upstream/emscripten/cache/wasm/include -DEMSCRIPTEN -fignore-exceptions -std=c++14 -c /home/sid/mumax-view/src/arrow.cpp -Xclang -isystem/home/sid/emsdk/upstream/emscripten/system/include/SDL -c -o CMakeFiles/mumax-view.dir/src/arrow.cpp.o -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr' failed (1)
make[2]: *** [CMakeFiles/mumax-view.dir/build.make:63: CMakeFiles/mumax-view.dir/src/arrow.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:76: CMakeFiles/mumax-view.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
`

Can you point me some help please?

Thanks

**Comment by JeroenMulkers** [comment]
You need to have the glm headers to compile mumax-view.

**Comment by sergiomtzlosa** [comment]
Thanks, I tried to get the headers with:

`sudo apt-get install libglm-dev`

but no luck, still fails on compiling. Should I set the path somewhere on the mumax-view code?

Regards

**Comment by JeroenMulkers** [comment]
Cmake should take care of that. Did you reconfigure cmake before running make again?

On a side note: if you are not planning to make changes to the code, then there is no reason to build mumax-view yourself. You can simply use the app on http://dynamag.ugent.be/mumax-view/

**Comment by sergiomtzlosa** [comment]
Hi,

Thank you, yoes I reconfigure it but still fails, I am planning to do a Docker with your code, then i would like to compile it from code.

Regards
